### ISSUE TITLE
Merciless Fighting Style problems

### ISSUE THREAD

**Issue by Rosgath** [SolastaMods/SolastaCommunityExpansion#1598]
I have been using the Merciless Fighting Style and have noticed that when the Extra Attack Triggers (From reducing a creature to 0 or fewer HP) it can cause some. . . unusual interactions. The following are the things that have happened:

1.) Gained a full extra Action (not just one extra Attack). Not sure what triggers this, but it can happen randomly.)
2.) When using Action Surge after this has triggered, I can only use attacks and cannot use a Full extra action.
3.) When a Bonus Action Attack reduces a creature to 0 or fewer HP, I seem to gain a full extra Action (this I have noticed does trigger consistently).

**Comment by ThyWoof** [comment]
Can you please share a save?

**Comment by Rosgath** [comment]
[AutoSave_7.zip](https://github.com/SolastaMods/SolastaCommunityExpansion/files/9338634/AutoSave_7.zip)

I had to zip it or else it wouldn't let me upload it.

I uploaded this specific auto save as it starts immediately on a fight where I experienced the 1st issue. To replicate it (or at least his is how it worked for me) the Fighter moved to attack the Archmage, using the Dash action to get there on it's first turn. I then used my Shield Bonus Action attack, then used Action Surge to attack 2 more times (the first attack of the Action surge used a Gambit dice if that matters). The second attack KO'd the Archmage and my fighter was given an additional full action to dash back to where he started from.

**Comment by dolenam317** [comment]
This is due to how additional action and action surge is implemented
1. The full action you described is the combination of 1 attack granted by merciless FS and other action left by your action surge. After you use 2 attacks your main action UI is hidden but the fact is the game still record that you haven't use dash, disengage etc so when the fighting style grant you another attack the UI is revealed again and make you feel that you have a full action.
2. This is hard to fix or impossible to fix considered how UI code and the code that filter your action is written. May be list other actions as forbidden can help but I am not so sure about that. It might interact weirdly with haste action by remove the ability to dash/disengage with haste action.

**Comment by Rosgath** [comment]
I think it may be best to leave it as is then, though I have to admit that the Merciless Fighting style in my game si far has felt... very strong when compared to others like GW FS. The extra Attack may be too much from a balance perspective.
