### ISSUE TITLE
User report from Nexus: Double ability bonus for pushing

### ISSUE THREAD

**Issue by ChrisPJohn** [SolastaMods/SolastaCommunityExpansion#590]
Dima793

The versions of Solasta, the Solasta Mod API, and Solasta Community Expansion.

﻿Solasta 1.2.15 - Public, Solasta Mod API 1.2.15.6, Solasta Community Expansion 1.2.15.7.

A list of other mods you have installed

SOLASTA DM Pro - Multiplayer 1.2.15.3, Divine Casting with Weapon and Shield 0.0.2.
A short description of the bug

Sorr-Akkath Saboteur has double the ability bonus for athletics when pushing. Extra bonus is reflected in the log as "+5: Sorr-Akkath Saboteur has: None".

A step-by-step procedure to reproduce it

Make player's character stand on an edge, let the enemy push it off a cliff. Conditions in which I experienced this bug:
Location: Caer Lem Outpost, after the rotating bridge, last fight of the "escape the caves" quest. Difficulty: Cataclysm, unmodified. The monster was fully lit, in case it's supposed to affect anything. Other monsters had proper modifiers.

The save, character and log files

Google drive folder: https://drive.google.com/drive/folders/1gFfwfI0sAQXlhEPeaUM-VZVjFfiYgWFc﻿.

**Comment by DubhHerder** [comment]
The saboteur has proficiency in athletics in the monster definition:

```skillScores": [
    {
      "$id": "3",
      "$type": "MonsterSkillProficiency, Assembly-CSharp",
      "skillName": "Athletics",
      "bonus": 5
    }```

And a feature definition `AbilityCheckAffinitySaboteurStrengthBonus` which grants

```
"$type": "FeatureDefinitionAbilityCheckAffinity, Assembly-CSharp",
  "affinityGroups": [
    {
      "$id": "1",
      "$type": "FeatureDefinitionAbilityCheckAffinity+AbilityCheckAffinityGroup, Assembly-CSharp",
      "abilityScoreName": "Strength",
      "proficiencyName": "Athletics",
      "abilityCheckModifierDiceNumber": 5
    }
  ],```

The feature uses "Feature/&NoContentTitle" for it's title and description which is where the "has : none" in the combat log is coming from. The bug should probably be reported in the official bug channel first as it's not caused by mods, could be reopened if the Devs ignore it after the report

**Comment by ThyWoof** [comment]
not a mod bug
