### ISSUE TITLE
Blind Sight fighting style not working

### ISSUE THREAD

**Issue by ChrisPJohn** [SolastaMods/SolastaCommunityExpansion#96]
dreastish:
Fighting Style:  Blindfighting seems to be broken.  When I cast fog cloud or darkness on enemies, my characters with the fighting style get double disadvantage instead of advantage when attacking them within 10'.

(Incidentally, the "use official SRD disadvantage/advantage" option seem to be broken as well, as these spells should neutralize all advantage and disadvantage under those rules, instead of providing double disadvantage to all attacks.  Blind + Invisible = ad + disad.)

**Comment by DubhHerder** [comment]
A possible character specific solution could be to make a character with the fighting style immune to ConditionHeavilyObscured and ConditionDarkness by adding a new FeatureDefinitionConditionAffinity similar to ConditionAffinityBlindnessImmunity

A general solution could be to have SenseBlindSight2  nullify CombatAffinityVeil and CombatAffinityHeavilyObscured by adding attribute similar to  

   var HeavilyObscured = DatabaseHelper.FeatureDefinitionCombatAffinitys.CombatAffinityHeavilyObscured;
            HeavilyObscured.NullifiedBySenses.Add(SenseMode.Type.Tremorsense);
            HeavilyObscured.NullifiedBySenses.Add(SenseMode.Type.Blindsight);

**Comment by ChrisPJohn** [comment]
Update from the user that reported the issue:

Yes, I looked into how these spells (heavy obscurement generating spells) are implemented for this game, and it looks like since this game’s advantage cancellation was removed by choice they decided to make heavy obscurement work as a pure disadvantage generator. I’m gonna need to mod heavy obscurement myself (or get someone to do it) to get it back to SRD standard (heavy obscurity should cause invisibility + blindness, which in SRD would then neutralize all advantage and disadvantage for everybody, but would do nothing with Solasta’s rules except prevent the casting of spells that require sight.  Exceptions would need to be put in place for being able to perceive through it in such a mod, of course).

So all I’d expect blindsight to do right now properly implemented would be to remove the disadvantage, not generate advantage, but even that would make a blindfighting strategy workable.  But it doesn’t do that.

(I'd also love it if fog cloud, darkness, cloudkill etc. would add invisibility to all people in their effect, since that would work well with the "use official SRD advantage rules" option, although still be imperfect with something like Devil's Sight when warlocks officially exist later.)

**Comment by dreast-collab** [comment]
I think, by far, the easiest way to implement this would be to replace the existing effects of fog cloud and darkness (and the obscuring effect of cloudkill) with invisibility + blindness for those inside.  If the senses are properly implemented that should fix most of the issue.  Two remain:  True Sight (and Devil's Sight), and blocking line of sight.

Technically, if an obscuring effect lies between two combatants, with neither inside the effect, it should block line of sight, unless a given combatant can see through it.  I'm not sure how to implement this because I haven't had time to dig into Solasta's code, but it's a rather edge case.

In addition, True Sight and any creature with Devil's Sight (Devils, Warlocks) distinguish between fog obscurity and darkness obscurity, which means the effects would need to be differentiated to support these sense modes.

However, for now, simply invisibility + blindness would seem to do the trick... though I say that without having looked at how Solasta is modded at all (my prior experience is with modding Baldur's Gate, pre-extended edition).

**Comment by Farowmir** [comment]
Adding some reports on my recent experience with Fighting Style: Blind Fighting pertaining to using the Blind Fighting Style along with a reach weapon on a character race that does not otherwise have darkvision.

For my report conditions the Solasta /CE Mod Version is: 1.3.57.4C and the Player controls a Human Fighter that has taken the Blind Fighting Style at level 1 fighter and wields a halberd as their reach weapon.

**Condition 1: (Blind Bridge)**
The Player's Fighter faces an unlit enemy that is 15ft away with the enemy and has disadvantage on their attack rolls due to targeting an unlit target outside of their blind sight. As the Fighter approaches the disadvantage from unlit enemy is removed when moving into 5ft melee range instead of the 10ft blind fighting distance.

**Condition 2: (Blind Elevation)**
The Player's Fighter faces an unlit enemy that is on one square lower elevation and then approaches but the disadvantage from unlit is not removed at the 10ft BFS range and is instead removed at the 5ft melee range.

**Condition 3: (Blind Wall)**
The Player's Fighter is 10ft away of an unlit enemy but has a 5ft tall wall separating them. The Fighter is able to attack the target at their 10ft reach but continues to have disadvantage when targeting an unlit enemy.

All conditions above should have the benefit of the Blind Fighting Style applied.

A .zip file containing saves for the conditions above is attached. [Testing (Blind Fighting).zip](https://github.com/SolastaMods/SolastaCommunityExpansion/files/8942024/Testing.Blind.Fighting.zip)
